apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-exporter
  template:
    metadata:
      labels:
        app: edge-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: exporter
        image: edge-metrics:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
